name: flutter_expandable_fab
description: Speed dial FAB that can show/hide multiple action buttons with animation.
version: 1.7.3
homepage: https://github.com/zuvola/flutter_expandable_fab

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
